### ISSUE TITLE
RATRATRATRAT

### ISSUE THREAD

**Issue by GurteX** [asphyxia1337/mioclient-me#3]
so after my own research i found this line of code... -

    final Setting<Boolean> place;
    final Setting<Target> target;
    final Setting<Float> placeRange;
    final Setting<Float> placeTrace;
    final Setting<Float> minDamage;
    final Setting<Integer> placeDelay;
    final Setting<Float> maxSelfP;
    final Setting<Float> facePlace;
    final Setting<Integer> multiPlace;
    final Setting<Boolean> countMin;
    final Setting<Boolean> antiSurr;
    final Setting<Boolean> newerVer;
    final Setting<Attack> attack;
    final Setting<Boolean> explode;
    final Setting<Float> breakRange;
    final Setting<Float> breakTrace;
    final Setting<Float> breakMinDmg;
    final Setting<Float> slowBreak;
    final Setting<Integer> slowDelay;
    final Setting<Integer> breakDelay;
    final Setting<Float> maxSelfB;
    final Setting<Boolean> instant;
    final Setting<Rotate> rotate;
    final Setting<Boolean> stay;
    final Setting<Boolean> multiThread;
    final Setting<Boolean> suicide;
    final Setting<Float> range;
    final Setting<Boolean> override;
    final Setting<Float> minFP;
    final Setting<Boolean> noFriendP;
    final Setting<AutoSwitch> autoSwitch;
    final Setting<Boolean> mainHand;
    final Setting<Bind> switchBind;
    final Setting<Boolean> switchBack;
    final Setting<SwingType> swing;
    final Setting<Float> pbTrace;
    final Setting<Boolean> setDead;
    final Setting<Float> targetRange;
    final Setting<Integer> cooldown;
    final Setting<Float> partialT;
    final Setting<Boolean> fallBack;
    final Setting<Float> fallbackDmg;
    final Setting<Boolean> soundR;
    final Setting<Boolean> holdFP;
    final Setting<Boolean> multiTask;
    final Setting<ThreadMode> threadMode;
    final Setting<Integer> threadDelay;
    final Setting<Boolean> predict;
    final Setting<Boolean> noParticles;
    final Setting<Boolean> pingBypass;
    final Setting<Integer> interpolate;
    private final DiscreteTimer placeTimer;
    private final DiscreteTimer breakTimer;
    private final Set<BlockPos> positions;
    private Calculation currentCalc;
    private EntityPlayer currentTarget;
    private Entity currentCrystal;
    private boolean tick;
    private boolean switching;
    final Map<Integer, EntityTime> killed;
    final Set<Integer> attacked;
    final Set<BlockPos> slow;
    final StopWatch renderTimer;
    final StopWatch threadTimer;
    final HelperBreak breakHelper;
    final HelperPlace placeHelper;
    float[] rotations;
    BlockPos renderPos;
    Runnable postRunnable;
    boolean confirmed;
    boolean setSafe;

This is literally a rat, please delete your git repo.

**Comment by cattyngmd** [comment]
so true.

basketbol

**Comment by asphyxia1337** [comment]
im so exposed

**Comment by CascadeDemon** [comment]
french
